### ISSUE TITLE
Safe Piece

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/eight-queens#1]
# Description
The initial phase requires us to check whether every piece on the board is safe or not i.e. none of the pieces are being attacked by other pieces.

## Sub-Feature
- Check for attacks across rows.
- Check for attacks across diagonals.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/106360343-ed47e980-633d-11eb-9b68-6e53d49b11d1.png)

## Dependencies
None

## Milestones
- [x] Develop a process to check for attacks across rows.
- [x] Develop a process to check for attacks across diagonals.
- [x] Develop unit tests to validate the implementations.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
