### ISSUE TITLE
Place Queen Pieces

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/eight-queens#3]
# Description
In this phase, we aim to place the queen pieces in the chessboard such that every piece on the board is safe (both horizontally and diagonally).

## Sub-Feature
- Accepts default chess-board positions or creates a new instance of the board.
- Assigns piece positions along with checking the safety of pieces in the board.
- Unit tests for the method that places queen pieces.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/106388767-01efb480-6406-11eb-8865-8bd46270508e.png)

## Dependencies
- Safe Piece #1 

## Milestones
- [x] Develop a method that accepts default chess-board positions or creates a new instance of the board.
- [x] Develop a method that assigns piece positions along with checking the safety of pieces in the board.
- [x] Develop unit tests for the method that places queen pieces on the board.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
