### ISSUE TITLE
Eight Queens Solution

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/eight-queens#5]
# Description
This phase involves using the backtracking algorithm to calculate every possible solution for the eight queens challenge set. It also involves comparing the calculated solutions with the list of every possible combination/solution in the challenge set.

## Sub-Feature
- Backtracking algorithm used to calculate possible solutions.
- Compare calculated solutions to every possible or available solution.
- Unit tests to check the developed methods.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/106394731-180c6d80-6424-11eb-984e-43a808d2b3fd.png)

## Dependencies
- Safe Piece #1 
- Place Queen Pieces #3 

## Milestones
- [x] Develop a backtracking algorithm used to calculate possible solutions.
- [x] Compare calculated solutions to every possible or available solution.
- [x] Develop unit tests to check the developed methods.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
